connect to testdb;

create schema todolist;

create table todolist.user (
    id bigint not null primary key generated by default as identity,
    username varchar(256),
    passhash varchar(512),
    email varchar(2048)
);

create table todolist.todo_list (
    id bigint not null primary key generated by default as identity,
    list_name varchar(256) not null unique
);

create table todolist.user_list (
    user_id bigint,
    list_id bigint,
    foreign key (user_id)
        references todolist.user(id)
        on delete cascade,
    foreign key (list_id)
        references todolist.todo_list(id)
        on delete cascade
);

create table todolist.todos (
    id bigint not null primary key generated by default as identity,
    summary varchar(256),
    details varchar(1024),
    done boolean,
    create_date timestamp default current_timestamp,
    complete_date timestamp default null,
    list_id bigint not null,
    foreign key (list_id)
        references todolist.todo_list(id)
        on delete cascade
);